package exam;

import java.util.Random;

import javax.microedition.lcdui.Command;
import javax.microedition.lcdui.CommandListener;
import javax.microedition.lcdui.Display;
import javax.microedition.lcdui.Displayable;
import javax.microedition.lcdui.Form;
import javax.microedition.lcdui.StringItem;
import javax.microedition.midlet.MIDlet;

public class RandomNumber extends MIDlet implements CommandListener{
	private Display display;
	private Command exit, generate;
	private StringItem item;
	private Form form;

	public RandomNumber(){
		display=Display.getDisplay(this);
		form = new Form("RandomNumber");
		exit = new Command("Exit", Command.EXIT,0);
		generate = new Command("Generate", Command.OK,1);		
		item = new StringItem("Number ","");
		form.addCommand(exit);
		form.addCommand(generate);
		form.setCommandListener(this);
		form.append("This Random Number Generated By Mr. Sandeep Kumar Suman, Software Developer, Roseindia Technology Pvt Ltd. Mobile No:+919313985248");
		form.append(item);
	}

	public void startApp(){
		display.setCurrent(form);
	}

	public void pauseApp(){}

	public void destroyApp(boolean unconditional){
		notifyDestroyed();
	}

	public void commandAction(Command c, Displayable d){
		String label = c.getLabel();
		if(label.equals("Exit")){
			destroyApp(false);
		}else if(label.equals("Generate")){
			random();
		}
	}

	public void random(){
		Random number = new Random();
		float f = number.nextFloat();
		number.setSeed(System.currentTimeMillis());		
		item.setText(""+(f*100.0f)%100);
	}
}